### ISSUE TITLE
Implement rounding of numerical values

### ISSUE THREAD

**Issue by gitcatpeter** [FoxxMD/komodo-utilities#1]
Thank you for the utilities.
Regarding ntfy utility, do you think you could implement rounding of some numerical values passed by Komodo?

Especially **CPU usage** is being reported as a raw value with so many insignificant digits.
Probably it is safe to say that every numerical value (so also RAM and disk usages) could be rounded just in case, before packing it back into JSON.

Personally I'd like no decimal points at all, but accuracy could be a docker environment parameter. 

See: https://github.com/mbecker20/komodo/issues/198

```
case "ServerCpu":
                    message.push(`Hit ${data.percentage}%`);
```

**Comment by FoxxMD** [comment]
I'll make this change next week, thanks for reporting it.

**Comment by FoxxMD** [comment]
Available for ntfy and gotify on `latest` tag

* CPU percent does not include any decimals
* GB for memory/disk includes up to 2 decimals
